"""empty message

Revision ID: 37f5a59ba212
Revises: 
Create Date: 2018-02-10 21:07:20.772166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f5a59ba212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=128), nullable=True),
    sa.Column('vector', sa.PickleType(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_features')
    # ### end Alembic commands ###
