"""empty message

Revision ID: 3b1266dc3e8a
Revises: c0d9c1405a1e
Create Date: 2018-02-10 09:10:31.258838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1266dc3e8a'
down_revision = 'c0d9c1405a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_photo_features_person_name'), 'photo_features', ['person_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_features_person_name'), table_name='photo_features')
    # ### end Alembic commands ###
