"""empty message

Revision ID: 715891bb0c8d
Revises: 4b2ad62d7378
Create Date: 2018-01-22 17:34:11.516399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715891bb0c8d'
down_revision = '4b2ad62d7378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('vector', sa.VARCHAR(length=128), nullable=True),
    sa.Column('model', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('photo_features')
    # ### end Alembic commands ###
