"""empty message

Revision ID: c0d9c1405a1e
Revises: f165ab671413
Create Date: 2018-02-09 21:54:14.017299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d9c1405a1e'
down_revision = 'f165ab671413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_features', sa.Column('filename', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_features', 'filename')
    # ### end Alembic commands ###
