"""empty message

Revision ID: f165ab671413
Revises: 715891bb0c8d
Create Date: 2018-01-22 20:44:46.074197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f165ab671413'
down_revision = '715891bb0c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_features', sa.Column('vector', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_features', 'vector')
    # ### end Alembic commands ###
